version: '3.4'

services:
  auth:
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
    ports:
      - "7210:8433"
    command:
      - start-dev
      - --hostname-port=7210
      - --features=token-exchange,declarative-user-profile
      - --import-realm
    volumes:
      - .data/keycloak:/opt/keycloak/data/h2/
      - build/keycloak/cert/server.crt.pem:/opt/keycloak/conf/server.crt.pem:ro
      - build/keycloak/cert/server.key.pem:/opt/keycloak/conf/server.key.pem:ro
      - build/keycloak/sample-realm.json:/opt/keycloak/data/import/sample-realm.json:ro

  email:
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - overlay

  auth-sample-weather-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "7212:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  auth-sample-weathersummary-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "7213:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  auth-sample-mvc-client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "7214:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  auth-sample-javascriptbff-client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "7215:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  auth-sample-react-client:
    ports:
      - "7216:7216"
