# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: auth
services:
- name: auth
  image: quay.io/keycloak/keycloak
  bindings:
  - name: https
    protocol: https
    port: 7210
    containerPort: 8443
  env:
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: admin
  - name: KC_HTTPS_CERTIFICATE_FILE
    value: /opt/keycloak/conf/server.crt.pem
  - name: KC_HTTPS_CERTIFICATE_KEY_FILE
    value: /opt/keycloak/conf/server.key.pem
  args:
    start-dev --hostname-port=7210 --features=token-exchange,declarative-user-profile --import-realm #--log-level=DEBUG
  volumes:
  - source: .data/keycloak
    target: /opt/keycloak/data/h2/
  - source: build/keycloak/cert/server.crt.pem
    target: /opt/keycloak/conf/server.crt.pem
  - source: build/keycloak/cert/server.key.pem
    target: /opt/keycloak/conf/server.key.pem
  - source: build/keycloak/sample-realm.json
    target: /opt/keycloak/data/import/sample-realm.json

- name: weather-api
  project: src/Samples.WeatherApi/Samples.WeatherApi.csproj
  bindings:
  - port: 7212
    protocol: https

- name: weather-summary-api
  project: src/Samples.WeatherSummaryApi/Samples.WeatherSummaryApi.csproj
  bindings:
  - port: 7213
    protocol: https

- name: mvc-client
  project: src/Samples.WeatherApi.MvcClient/Samples.WeatherApi.MvcClient.csproj
  bindings:
  - port: 7214
    protocol: https

- name: javascriptbff-client
  project: src/Samples.WeatherApi.JavaScriptBffClient/Samples.WeatherApi.JavaScriptBffClient.csproj
  bindings:
  - port: 7215
    protocol: https

- name: email
  image: mailhog/mailhog
  bindings:
  - name: smtp
    port: 1025
    protocol: smtp
    containerPort: 1025
  - name: panel
    port: 8025
    protocol: http
    containerPort: 8025
